version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
